[workspace]
resolver = "2"
members = [
    "contracts/invoice-registry",
    "contracts/settlement-orchestrator",
    "contracts/netting-attestation",
    "contracts/policy-adapter",
]

[workspace.package]
edition = "2021"
version = "0.1.0"
publish = false

[workspace.dependencies]
soroban-sdk = "27.0.6"

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[profile.release-with-logs]
inherits = "release"
debug-assertions = true
